# Generated by Django 4.0.4 on 2022-05-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_point_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Категории'),
        ),
    ]
